### ISSUE TITLE
webhook uses wrong main method

### ISSUE THREAD

**Issue by mattmoor** [knative/sample-controller#256]
I noticed playing around with a derivative of this that the webhook isn't using the webhook main method, and so all API server calls fail with connection refused (because it ain't listening).

We should switch `./cmd/webhook/main.go` to use the proper webhook main method.

cc @pmorie 

/kind good-first-issue

**Comment by MIBc** [comment]
I'd like to try.

**Comment by mattmoor** [comment]
Go for it!
